services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks:
      - regnum-network
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - regnum-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - regnum-network
  regnum-mmorpg:
    build: .
    ports:
      - "3223:3223"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb
    networks:
      - regnum-network

networks:
  regnum-network:
    driver: bridge