services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
  regnum-mmorpg:
    build: .
    ports:
      - "3223:3223"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis