name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Sync files to server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 168.119.196.69 >> ~/.ssh/known_hosts
        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./ root@168.119.196.69:/root/docker/regnum-mapgame/

    - name: Run deployment commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 168.119.196.69
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/docker/regnum-mapgame
          docker compose down
          docker compose up --build -d --remove-orphans